# Generated by Django 4.1.6 on 2023-02-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=5000)),
                ('read_date', models.DateField()),
                ('my_thoughts', models.TextField(blank=True, default='', max_length=10000)),
            ],
        ),
    ]
