# Generated by Django 4.1.6 on 2023-02-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverimage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
