# Generated by Django 4.1.2 on 2023-02-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0003_author_book_isbn_book_date_published_book_date_read_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="ISBN",),
        migrations.RemoveField(model_name="book", name="read_date",),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=13,
                null=True,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
    ]
