# Generated by Django 4.1 on 2023-02-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_book_isbn_remove_book_read_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="born",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="death",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="book",
            name="date_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="date_read",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
