# Generated by Django 4.1 on 2023-02-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_book_isbn_remove_book_read_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="born",
        ),
        migrations.RemoveField(
            model_name="author",
            name="death",
        ),
        migrations.RemoveField(
            model_name="book",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="book",
            name="date_read",
        ),
        migrations.AddField(
            model_name="author",
            name="born_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="death_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="year_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="year_read",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.author",
            ),
        ),
    ]
